### ISSUE TITLE
Can I use this xsdformeditor parser in my project ?

### ISSUE THREAD

**Issue by tanveer-ali** [janstafa/XsdFormEditor#1]
Hi,

Can I use this xsdformeditor project in my project and modify if required ? Please reply me.

Thanks

Tanveer

**Comment by janstafa** [comment]
Hi Tanveer,

Feel free to fork it. If you make some improvements to the code please raise a pull request.

Thank you for your interest.
Jan

**Comment by tanveer-ali** [comment]
Hi,

Thanks Jan. I don't know this will be some improvements but I will need to add some field for customization in parser and I will use this with one mvcdynamicforms project to generate html form from xsd.

**Comment by janstafa** [comment]
Sure, no problem :)
